name: Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v0.4.3
        with:
          host: 65.2.166.24
          username: ubuntu
          key: ${{ secrets.MYSECRETKEY1 }}
          port: 22
          script: |
            # Navigate to your project directory
            cd /home/ubuntu/backend

            # Pull the latest code from the GitHub repository
            git pull

            # Restart the PM2 service
            pm2 restart app.js
