name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$MYPRIVATEKEY1" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 65.2.166.24 >> ~/.ssh/known_hosts
        env:
          MYPRIVATEKEY1: ${{ secrets.MYPRIVATEKEY1 }}
        
      - name: Pull code and restart PM2
        run: |
          ssh ubuntu@65.2.166.24 "cd /home/ubuntu/backend && git pull origin main && pm2 restart app.js"
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
